name: Test setup
runs:
  using: "composite"
  steps:
    - name: Setup GCC
      uses: Dup4/actions-setup-gcc@v1
      with:
        version: latest

    - name: rust-cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
          ~/.rustup/
        key: rust-1.79.0-${{ hashFiles('**/Cargo.toml') }}
        restore-keys: rust-1.79.0-

    - name: Setup toolchain
      id: rustc-toolchain
      shell: bash
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain 1.79.0 -y
